#!/bin/bash
# chkconfig: 2345 30 70 
# description: Starts and Stops oracle.

 
case "$1" in 
	start) 
		echo "Starting Oracle Listener and Database ... " 
		echo "----------------------------------------------------------------------" >> /var/log/orac
		date +" %T %a %D : Starting Oracle Listener and Database ... " >> /var/log/oracle 
		echo "----------------------------------------------------------------------" >> /var/log/orac
		su - oracle -c dbstartup >> /var/log/oracle 
		echo "Done." 
		echo "" 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		date +" %T %a %D :Finished." >>/var/log/oracle 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		touch /var/lock/subsys/oracle 
		;; 
	stop) 
		echo "Stop Oracle  Database and Listener ... " 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		date +" %T %a %D : Stop Oracle Listener and Databases ..." >> /var/log/oracle 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		su - oracle -c dbstop >> /var/log/oracle 
		rm -f /var/lock/subsys/oracle 
		echo "Done." 
		echo "" 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		date +" %T %a %D : Finished." >> /var/log/oracle 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
     ;;
	restart) 
		echo "Restarting Oracle Listener and Database ..." 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		date +" %T %a %D : Restart ing Oracle Listener and Databases ..." >> /var/log/oracle 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		su - oracle -c dbstop >> /var/log/oracle 
		su - oracle -c dbstartup >> /var/log/oracle 
		echo "Done." 
		echo "" 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		date +" %T %a %D : Finished." >> /var/log/oracle 
		echo "---------------------------------------------------------------------" >> /var/log/oracle 
		touch /var/lock/subsys/oracle 
		;; 
	*) 
		echo "Usage: oracle {start|stop|restart}" 
		exit 1 
 esac 
 
